### ISSUE TITLE
Editing other tags like h2 h3 etc

### ISSUE THREAD

**Issue by eedeidk** [dougmassay/tagmechanic-sigil-plugin#2]
How do I edit a tag to something not specified in the list of tags?
 previous versions had this feature but when I try to remove and install old (4.5) I am getting this error.

```
Status: failed

Traceback (most recent call last):
  File "/usr/local/share/sigil/plugin_launchers/python/launcher.py", line 142, in launch
    self.exitcode = target_script.run(container)
  File "/home/ecophene/.local/share/sigil-ebook/sigil/plugins/TagMechanic/plugin.py", line 586, in run
    guiMain(root, bk).pack(fill=tkinter_constants.BOTH)
  File "/home/ecophene/.local/share/sigil-ebook/sigil/plugins/TagMechanic/plugin.py", line 149, in __init__
    self.initUI()
  File "/home/ecophene/.local/share/sigil-ebook/sigil/plugins/TagMechanic/plugin.py", line 288, in initUI
    self.parent.geometry(self.misc_prefs['windowGeometry'])
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2035, in wm_geometry
    return self.tk.call('wm', 'geometry', self._w, newGeometry)
_tkinter.TclError: bad geometry specifier "01d9d0cb00030000000006070000004e000007ff000002670000060700000068000007ff00000267000000000000000005560000060700000068000007ff00000267"
Error: bad geometry specifier "01d9d0cb00030000000006070000004e000007ff000002670000060700000068000007ff00000267000000000000000005560000060700000068000007ff00000267"
```
Is there any workaround? I tried to modify 'strong' tags to 'h2' tags. Previously I was able to do that but after update the option is not available to manually enter the tag.. Please Help.

**Comment by dougmassay** [comment]
Previous versions only ever had that feature accidentally. I had no idea people were able to manually enter tags into the tkinter dropdown boxes and have it work.

If you want to roll back to a previous version of the plugin, you'll need to edit the plugin's json preferences file and remove the geometry entry. But that can be a bit fiddly if you don't know the syntax. Probably easiest to remove the json file entirely. The 'Open Preferences' button in the bottom left corner of the 'Manage Plugins' dialog box will get you most of the way there. From there it's 'plugin_prefs/tagmechanic'. Delete the tagmechanic.json file. That will get rid of the bad geometry error when launching the plugin.

**Comment by BeckyDTP** [comment]
Oh ...

@dougmassay:
After all, you did not write the most important thing - that in the older (4.x) and in the newer (5.x) versions, you can edit possible element replacements.

@eedeidk:
* In an older version, RIGHT click on the plugin main window and select "Customize Plugin".
* In a newer version, open the "Edit" menu in the plugin window and select "Config".

Manual typing takes unnecessary time. Probably better to enter once and choose from the list.

**Comment by dougmassay** [comment]
You're right. The OP's use case (changing strong tags to h tags) is perfectly doable in the newer version as well. I thought they were referring to manually entering the _from_ tag in the dropdown box. I've gotten reports that THAT will work in the old version as well (unbeknownst to me). Essentially working around the issue of being unable to add to the list of editable source tags without modifying the python code.

**Comment by eedeidk** [comment]
Ok got it. Thanks, @BeckyDTP @dougmassay  . 
Well how do I --

1. Modify 'h1', 'h2', (The customize menu doesn't seem to have: **Choices to change 'h1' elements to:** )
2. Completely destroy a Tag and it's contents (Like in _BeautifulSoup_ _decompose_ method). The delete method currently only _unwraps_ the tag.
3. Remove empty tags.

Kindly include this feature if not available now. Thanks for this useful plugin @dougmassay .

**Comment by dougmassay** [comment]
1) You don't right now. Not without editing python code, anyway. I hope to change this in the future, but don't count on it being soon. Feel free to revert to the earlier version if you need that functionality in the meantime.

2) You don't. The plugin, by design, won't touch content. It only modifies/deletes tags. That won't be changing.

3) I don't quite follow. But if you mean tags with no content, then again, the plugin won't be affecting, or using for selection criteria, any content (or lack thereof). Tags and their attributes only. Tags that contain no content present no difficulty finding and removing with normal search and replace. This plugin was created to handle situations where a non-parsing Find & Replace isn't well suited to handling complex nesting safely.
